services:
    yaml:
        class: Symfony\Component\Yaml\Parser
    markdown:
        class: Parsedown
    zz_chez_zzortell.notebook.manager:
        class: Zz\ChezZzortellBundle\Entity\NoteManager
        arguments: [@kernel, @validator, @yaml, @markdown]
