zz_chez_zz_freelance:
    path:     /
    defaults: { _controller: ZzChezZzortellBundle:Index:freelance }
zz_chez_zz_portfolio:
    path:     /portfolio
    defaults: { _controller: ZzChezZzortellBundle:Index:portfolio }
zz_chez_zz_libraries:
    path:     /libraries
    defaults: { _controller: ZzChezZzortellBundle:Index:libraries }
zz_chez_zz_notebook:
    path:     /notebook/{page}
    defaults: { _controller: ZzChezZzortellBundle:Notebook:notebook, tag: null, page: 1 }
    requirements:
        page: \d+
zz_chez_zz_notebook_note:
    path:     /notebook/note/{id}
    defaults: { _controller: ZzChezZzortellBundle:Notebook:note }
    requirements:
        id:   \d+
zz_chez_zz_notebook_tag:
    path:     /notebook/{tag}/{page}
    defaults: { _controller: ZzChezZzortellBundle:Notebook:notebook, tag: null, page: 1 }
    requirements:
        page: \d+
zz_chez_zz_articles:
    path:     /articles
    defaults: { _controller: ZzChezZzortellBundle:Articles:index }
